import * as fs from "node:fs/promises";
import * as path from "node:path";
import type {
  AgentifyIR,
  Capability,
  Domain,
  Emitter,
  EmitterOptions,
  EmitterResult,
} from "../types";

export class AgentsMdEmitter implements Emitter {
  readonly name = "agents-md";
  readonly format = "agents.md";

  async emit(ir: AgentifyIR, options: EmitterOptions): Promise<EmitterResult> {
    const outputDir = path.resolve(options.outputDir);
    await fs.mkdir(outputDir, { recursive: true });

    const content = generateAgentsMd(ir);
    const filePath = path.join(outputDir, "AGENTS.md");
    await fs.writeFile(filePath, content, "utf-8");

    return {
      format: this.format,
      filesWritten: [filePath],
      warnings: [],
    };
  }
}

function generateAgentsMd(ir: AgentifyIR): string {
  const sections: string[] = [];

  // AGENTS.md follows the Linux Foundation / Agentic AI Foundation standard
  sections.push(`# ${ir.product.name}`);
  sections.push("");
  sections.push(`> Generated by [Agentify](https://github.com/koriyoshi2041/agentify) — Agent Interface Compiler`);
  sections.push("");
  sections.push(ir.product.description);
  sections.push("");

  // Identity
  sections.push("## Identity");
  sections.push("");
  sections.push(`- **Name:** ${ir.product.name}`);
  sections.push(`- **Version:** ${ir.product.version}`);
  sections.push(`- **Base URL:** \`${ir.product.baseUrl}\``);
  if (ir.product.docsUrl) {
    sections.push(`- **Documentation:** ${ir.product.docsUrl}`);
  }
  if (ir.product.license) {
    sections.push(`- **License:** ${ir.product.license}`);
  }
  sections.push("");

  // Capabilities
  sections.push("## Capabilities");
  sections.push("");
  sections.push(`This API exposes ${ir.capabilities.length} operations across ${ir.domains.length} domains.`);
  sections.push("");

  for (const domain of ir.domains) {
    const caps = ir.capabilities.filter(c => c.domain === domain.name);
    sections.push(...renderDomainCapabilities(domain, caps));
  }

  // Auth
  sections.push("## Authentication");
  sections.push("");
  if (ir.auth.type === "none") {
    sections.push("No authentication required.");
  } else {
    sections.push(`**Type:** ${ir.auth.type}`);
    sections.push("");
    sections.push(`**Environment Variable:** \`${ir.auth.envVariable}\``);
    if (ir.auth.description) {
      sections.push("");
      sections.push(ir.auth.description);
    }
  }
  sections.push("");

  // Protocols
  sections.push("## Protocols");
  sections.push("");
  sections.push("### MCP (Model Context Protocol)");
  sections.push("");
  sections.push("This API is available as an MCP server. Start it with:");
  sections.push("");
  sections.push("```bash");
  sections.push("npm start");
  sections.push("```");
  sections.push("");
  sections.push("The server exposes tools via stdio transport, compatible with Claude Desktop, Claude Code, and other MCP clients.");
  sections.push("");

  // Constraints
  sections.push("## Constraints");
  sections.push("");
  sections.push("- All requests must include appropriate Content-Type headers");
  sections.push("- Rate limits may apply — check API documentation for details");
  if (ir.auth.type !== "none") {
    sections.push(`- Authentication is required for all endpoints (${ir.auth.type})`);
  }

  const sideEffectOps = ir.capabilities.filter(c => c.sideEffects);
  if (sideEffectOps.length > 0) {
    sections.push(`- ${sideEffectOps.length} operations have side effects (create, update, delete) — use with caution`);
  }
  sections.push("");

  // Context
  sections.push("## Context");
  sections.push("");
  sections.push(`- **API Scale:** ${ir.strategy.scale} (${ir.strategy.endpointCount} endpoints)`);
  sections.push(`- **Generation Strategy:** ${ir.strategy.reason}`);
  sections.push(`- **Domains:** ${ir.domains.map(d => `${capitalize(d.name)} (${d.capabilityIds.length})`).join(", ")}`);
  sections.push("");

  return sections.join("\n");
}

function renderDomainCapabilities(domain: Domain, caps: readonly Capability[]): string[] {
  const lines: string[] = [];

  lines.push(`### ${capitalize(domain.name)}`);
  lines.push("");

  for (const cap of caps) {
    lines.push(`- **\`${cap.name}\`** — ${cap.http.method.toUpperCase()} \`${cap.http.path}\``);
    if (cap.description) {
      lines.push(`  ${truncate(cap.description, 120)}`);
    }
  }

  lines.push("");
  return lines;
}

function capitalize(str: string): string {
  return str.charAt(0).toUpperCase() + str.slice(1);
}

function truncate(str: string, maxLen: number): string {
  return str.length > maxLen ? str.slice(0, maxLen - 3) + "..." : str;
}
