import Handlebars from "handlebars";
import * as fs from "node:fs/promises";
import * as path from "node:path";
import type {
  AgentifyIR,
  Capability,
  Emitter,
  EmitterOptions,
  EmitterResult,
} from "../types";
import { scanMultipleFiles } from "../security/scanner";

export class MCPServerEmitter implements Emitter {
  readonly name = "mcp-server";
  readonly format = "mcp";

  async emit(ir: AgentifyIR, options: EmitterOptions): Promise<EmitterResult> {
    const warnings: string[] = [];
    const filesWritten: string[] = [];

    const outputDir = path.resolve(options.outputDir);
    const srcDir = path.join(outputDir, "src");

    await fs.mkdir(srcDir, { recursive: true });

    const filesToWrite = this.generateFiles(ir);

    const scanResult = scanMultipleFiles(filesToWrite);
    if (!scanResult.passed) {
      const criticals = scanResult.violations
        .filter(v => v.severity === "critical")
        .map(v => v.message);
      throw new Error(
        `Security scan FAILED with ${criticals.length} critical violation(s):\n${criticals.join("\n")}`,
      );
    }

    for (const v of scanResult.violations) {
      warnings.push(`[SECURITY:${v.severity}] ${v.message}`);
    }

    for (const [filePath, content] of filesToWrite) {
      const fullPath = path.join(outputDir, filePath);
      await fs.mkdir(path.dirname(fullPath), { recursive: true });
      await fs.writeFile(fullPath, content, "utf-8");
      filesWritten.push(fullPath);
    }

    return {
      format: this.format,
      filesWritten,
      warnings,
    };
  }

  private generateFiles(ir: AgentifyIR): Map<string, string> {
    const files = new Map<string, string>();

    files.set("src/index.ts", this.generateServerSource(ir));
    files.set("src/tools.ts", this.generateToolDefinitions(ir));
    files.set("src/handlers.ts", this.generateToolHandlers(ir));
    files.set("package.json", this.generatePackageJson(ir));
    files.set("tsconfig.json", this.generateTsConfig());
    files.set("Dockerfile", this.generateDockerfile(ir));
    files.set(".env.example", this.generateEnvExample(ir));
    files.set("README.md", this.generateReadme(ir));

    return files;
  }

  private generateServerSource(ir: AgentifyIR): string {
    const template = Handlebars.compile(SERVER_TEMPLATE);
    return template({
      productName: ir.product.name,
      productDescription: ir.product.description,
      toolCount: ir.capabilities.length,
    });
  }

  private generateToolDefinitions(ir: AgentifyIR): string {
    const template = Handlebars.compile(TOOLS_TEMPLATE);
    const tools = ir.capabilities.map(cap => ({
      name: cap.name,
      description: truncate(cap.agentDescription || cap.description, 200),
      inputSchema: JSON.stringify(cap.input.jsonSchema ?? { type: "object", properties: {} }, null, 2),
    }));
    return template({ tools });
  }

  private generateToolHandlers(ir: AgentifyIR): string {
    const template = Handlebars.compile(HANDLERS_TEMPLATE);
    const tools = ir.capabilities.map(cap => ({
      name: cap.name,
      method: cap.http.method.toUpperCase(),
      path: cap.http.path,
      baseUrl: cap.http.baseUrl,
      hasBody: cap.http.method !== "get" && cap.http.method !== "delete" && cap.http.method !== "head",
      contentType: cap.http.contentType ?? "application/json",
      pathParams: extractPathParams(cap.http.path),
      queryParams: cap.input.properties
        .filter(p => !cap.http.path.includes(`{${p.name}}`))
        .filter(p => cap.http.method === "get" || isQueryParam(p.name, cap))
        .map(p => p.name),
      bodyParams: cap.input.properties
        .filter(p => !cap.http.path.includes(`{${p.name}}`))
        .filter(p => cap.http.method !== "get" && !isQueryParam(p.name, cap))
        .map(p => p.name),
    }));

    return template({
      tools,
      baseUrl: ir.product.baseUrl,
      authType: ir.auth.type,
      authEnvVar: ir.auth.envVariable,
      authHeaderName: ir.auth.headerName ?? "Authorization",
      authScheme: ir.auth.scheme ?? "Bearer",
    });
  }

  private generatePackageJson(ir: AgentifyIR): string {
    const name = toKebabCase(ir.product.name) + "-mcp-server";
    return JSON.stringify(
      {
        name,
        version: "0.1.0",
        description: `MCP Server for ${ir.product.name} — generated by Agentify`,
        type: "module",
        scripts: {
          start: "tsx src/index.ts",
          build: "tsc",
          dev: "tsx watch src/index.ts",
        },
        dependencies: {
          "@modelcontextprotocol/sdk": "^1.27.1",
          "zod": "^4.3.6",
        },
        devDependencies: {
          typescript: "^5.8.3",
          tsx: "^4.19.4",
          "@types/node": "^22.15.2",
        },
      },
      null,
      2,
    );
  }

  private generateTsConfig(): string {
    return JSON.stringify(
      {
        compilerOptions: {
          target: "ES2022",
          module: "ESNext",
          moduleResolution: "bundler",
          lib: ["ES2022"],
          outDir: "./dist",
          rootDir: "./src",
          strict: true,
          esModuleInterop: true,
          skipLibCheck: true,
          resolveJsonModule: true,
          declaration: true,
          sourceMap: true,
        },
        include: ["src/**/*"],
      },
      null,
      2,
    );
  }

  private generateDockerfile(ir: AgentifyIR): string {
    const template = Handlebars.compile(DOCKERFILE_TEMPLATE);
    return template({ productName: ir.product.name });
  }

  private generateEnvExample(ir: AgentifyIR): string {
    const lines = [
      `# ${ir.product.name} MCP Server Configuration`,
      `# Generated by Agentify`,
      "",
    ];

    if (ir.auth.type !== "none") {
      lines.push(`# Authentication (${ir.auth.type})`);
      lines.push(`${ir.auth.envVariable}=your-key-here`);
      lines.push("");
    }

    lines.push("# Server Configuration");
    lines.push(`API_BASE_URL=${ir.product.baseUrl}`);
    lines.push("MCP_SERVER_PORT=3000");
    lines.push("");

    return lines.join("\n");
  }

  private generateReadme(ir: AgentifyIR): string {
    const template = Handlebars.compile(README_TEMPLATE);
    return template({
      productName: ir.product.name,
      productDescription: ir.product.description,
      toolCount: ir.capabilities.length,
      domains: ir.domains.map(d => ({
        name: d.name,
        count: d.capabilityIds.length,
      })),
      authType: ir.auth.type,
      authEnvVar: ir.auth.envVariable,
      strategy: ir.strategy,
      hasAuth: ir.auth.type !== "none",
    });
  }
}

// ─── Helpers ─────────────────────────────────

function truncate(str: string, maxLen: number): string {
  return str.length > maxLen ? str.slice(0, maxLen - 3) + "..." : str;
}

function toKebabCase(str: string): string {
  return str
    .replace(/([a-z])([A-Z])/g, "$1-$2")
    .replace(/[^a-zA-Z0-9]/g, "-")
    .replace(/-+/g, "-")
    .replace(/^-|-$/g, "")
    .toLowerCase();
}

function extractPathParams(pathStr: string): string[] {
  const matches = pathStr.match(/\{(\w+)\}/g);
  return matches ? matches.map(m => m.slice(1, -1)) : [];
}

function isQueryParam(paramName: string, cap: Capability): boolean {
  return cap.http.path.includes(`{${paramName}}`) === false
    && (cap.http.method === "get" || cap.http.method === "delete" || cap.http.method === "head");
}

// ─── Templates ───────────────────────────────

const SERVER_TEMPLATE = `import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { StdioServerTransport } from "@modelcontextprotocol/sdk/server/stdio.js";
import { registerTools } from "./tools";

const server = new McpServer({
  name: "{{productName}}",
  version: "0.1.0",
});

registerTools(server);

async function main() {
  const transport = new StdioServerTransport();
  await server.connect(transport);
  console.error("{{productName}} MCP Server running ({{toolCount}} tools)");
}

main().catch((error) => {
  console.error("Fatal error:", error);
  process.exit(1);
});
`;

const TOOLS_TEMPLATE = `import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { z } from "zod";
import { handleToolCall } from "./handlers";

export function registerTools(server: McpServer): void {
{{#each tools}}
  server.tool(
    "{{name}}",
    "{{description}}",
    {{{inputSchema}}},
    async (params) => handleToolCall("{{name}}", params),
  );

{{/each}}
}
`;

const HANDLERS_TEMPLATE = `const BASE_URL = process.env.API_BASE_URL ?? "{{baseUrl}}";
{{#if (isNot authType "none")}}
const AUTH_KEY = process.env.{{authEnvVar}} ?? "";
{{/if}}

interface ToolResult {
  content: Array<{ type: "text"; text: string }>;
  isError?: boolean;
}

export async function handleToolCall(
  toolName: string,
  params: Record<string, unknown>,
): Promise<ToolResult> {
  try {
    const handler = HANDLERS[toolName];
    if (!handler) {
      return errorResult(\`Unknown tool: \${toolName}\`);
    }
    return await handler(params);
  } catch (err) {
    const message = err instanceof Error ? err.message : String(err);
    return errorResult(\`Tool \${toolName} failed: \${message}\`);
  }
}

function errorResult(message: string): ToolResult {
  return {
    content: [{ type: "text", text: message }],
    isError: true,
  };
}

function successResult(data: unknown): ToolResult {
  return {
    content: [{
      type: "text",
      text: typeof data === "string" ? data : JSON.stringify(data, null, 2),
    }],
  };
}

async function apiRequest(
  method: string,
  path: string,
  params?: Record<string, unknown>,
): Promise<unknown> {
  let url = BASE_URL + path;

  const usedKeys = new Set<string>();

  // Replace path parameters
  if (params) {
    for (const [key, value] of Object.entries(params)) {
      const placeholder = \`{\${key}}\`;
      if (url.includes(placeholder)) {
        url = url.replace(placeholder, encodeURIComponent(String(value)));
        usedKeys.add(key);
      }
    }
  }

  // Add query parameters for GET/DELETE/HEAD requests
  if (params && (method === "GET" || method === "DELETE" || method === "HEAD")) {
    const queryEntries: string[] = [];
    for (const [key, value] of Object.entries(params)) {
      if (!usedKeys.has(key) && value !== undefined) {
        queryEntries.push(\`\${encodeURIComponent(key)}=\${encodeURIComponent(String(value))}\`);
      }
    }
    if (queryEntries.length > 0) {
      url += "?" + queryEntries.join("&");
    }
  }

  const headers: Record<string, string> = {
    "Content-Type": "application/json",
    "Accept": "application/json",
  };

{{#if (isNot authType "none")}}
{{#if (eq authType "bearer")}}
  if (AUTH_KEY) {
    headers["Authorization"] = \`{{authScheme}} \${AUTH_KEY}\`;
  }
{{else if (eq authType "apiKey")}}
  if (AUTH_KEY) {
    headers["{{authHeaderName}}"] = AUTH_KEY;
  }
{{else if (eq authType "basic")}}
  if (AUTH_KEY) {
    headers["Authorization"] = \`Basic \${AUTH_KEY}\`;
  }
{{else}}
  if (AUTH_KEY) {
    headers["Authorization"] = AUTH_KEY;
  }
{{/if}}
{{/if}}

  const fetchOptions: RequestInit = {
    method: method.toUpperCase(),
    headers,
  };

  if (method !== "GET" && method !== "DELETE" && method !== "HEAD" && params) {
    // Separate path params from body params
    const bodyParams: Record<string, unknown> = {};
    for (const [key, value] of Object.entries(params)) {
      if (!usedKeys.has(key)) {
        bodyParams[key] = value;
      }
    }
    if (Object.keys(bodyParams).length > 0) {
      fetchOptions.body = JSON.stringify(bodyParams);
    }
  }

  const response = await fetch(url, fetchOptions);

  if (!response.ok) {
    const errorText = await response.text();
    throw new Error(\`API error \${response.status}: \${errorText}\`);
  }

  const contentType = response.headers.get("content-type") ?? "";
  if (contentType.includes("application/json")) {
    return response.json();
  }
  return response.text();
}

const HANDLERS: Record<string, (params: Record<string, unknown>) => Promise<ToolResult>> = {
{{#each tools}}
  "{{name}}": async (params) => {
    const result = await apiRequest("{{method}}", "{{path}}", params);
    return successResult(result);
  },
{{/each}}
};
`;

const DOCKERFILE_TEMPLATE = `FROM node:20-slim AS builder
WORKDIR /app
COPY package*.json ./
RUN npm ci
COPY . .
RUN npm run build

FROM node:20-slim
WORKDIR /app
COPY --from=builder /app/dist ./dist
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/package.json ./

ENV NODE_ENV=production
EXPOSE 3000

# Health check
HEALTHCHECK --interval=30s --timeout=5s \\
  CMD node -e "console.log('ok')" || exit 1

CMD ["node", "dist/index.js"]
`;

const README_TEMPLATE = `# {{productName}} MCP Server

> Generated by [Agentify](https://github.com/koriyoshi2041/agentify) — Agent Interface Compiler

{{productDescription}}

## Quick Start

\\\`\\\`\\\`bash
# Install dependencies
npm install

# Configure environment
cp .env.example .env
# Edit .env with your credentials

# Start the server
npm start
\\\`\\\`\\\`

## Tools ({{toolCount}})

{{#each domains}}
### {{name}} ({{count}} tools)
{{/each}}

{{#if hasAuth}}
## Authentication

This server requires **{{authType}}** authentication.

Set the \\\`{{authEnvVar}}\\\` environment variable:

\\\`\\\`\\\`bash
export {{authEnvVar}}=your-key-here
\\\`\\\`\\\`
{{/if}}

## Strategy

{{strategy.reason}}

## Usage with Claude Desktop

Add to your Claude Desktop config (\\\`claude_desktop_config.json\\\`):

\\\`\\\`\\\`json
{
  "mcpServers": {
    "{{productName}}": {
      "command": "npx",
      "args": ["tsx", "src/index.ts"],
      "cwd": "/path/to/this/directory"
    }
  }
}
\\\`\\\`\\\`

---

*Generated by Agentify — One command. Every agent speaks your product.*
`;

// Register Handlebars helpers
Handlebars.registerHelper("eq", (a: unknown, b: unknown) => a === b);
Handlebars.registerHelper("isNot", (a: unknown, b: unknown) => a !== b);
